import { createAgentWorkforceDocument, type AgentInput, type SkillInput } from "./agent-workforce.ts";

type Seed = Partial<AgentInput> & Pick<AgentInput, "id" | "type" | "name" | "role" | "department" | "mission" | "personality">;

// Every field an agent needs, so a seed entry only states what is true of it.
const agent = (seed: Seed): AgentInput => ({
  parent_id: null,
  emoji: "◆",
  status: "planned",
  progress: 0,
  autonomy: "internal",
  cadence: "",
  schedule: "",
  triggers: [],
  responsibilities: [],
  capabilities: [],
  inputs: [],
  outputs: [],
  next_milestone: "",
  notes: "",
  ...seed,
});

const core = (seed: Omit<Seed, "type">) => agent({ ...seed, type: "core", parent_id: null });
const sub = (parent: string, seed: Omit<Seed, "type" | "parent_id">) => agent({ ...seed, type: "subagent", parent_id: parent });

const MAYA = "maya-content-director";
const CORA = "cora-client-success";
const STERLING = "sterling-sales-director";
const FORGE = "forge-systems-director";

const skill = (value: Omit<SkillInput, "quality_rating" | "review_count" | "provenance">): SkillInput => ({
  ...value,
  provenance: "starter_recommendation",
  quality_rating: null,
  review_count: 0,
});

export const DEFAULT_AGENT_SKILLS: SkillInput[] = [
  skill({
    id: "grounded-citations",
    name: "Grounded Citations",
    purpose: "Research claims against verifiable sources and keep citations attached to the answer.",
    behavior: "Collect claims, verify them against accessible sources, and return conclusions with citations attached.",
    capabilities: ["Source discovery", "Claim verification", "Citation formatting"],
    inputs: ["A bounded research question", "Candidate sources"],
    outputs: ["A cited answer", "A list of verification gaps"],
    documentation: "Starter documentation summary. Review the linked SKILL.md before configuring this recommendation.",
    category: "Research",
    tags: ["research", "citations", "evidence"],
    agent_ids: [],
    deployment_state: "draft",
    source_url: "https://github.com/NousResearch/hermes-agent/blob/main/skills/research/grounded-citations/SKILL.md",
  }),
  skill({
    id: "google-workspace",
    name: "Google Workspace",
    purpose: "Work safely with Gmail, Calendar, Drive, Docs, and Sheets using authenticated Google tools.",
    behavior: "Use authenticated Google tools to read or draft workspace content within the owner-approved scope.",
    capabilities: ["Gmail workflows", "Calendar workflows", "Drive and document workflows"],
    inputs: ["An owner-authorized workspace request", "Authenticated Google connection"],
    outputs: ["Requested workspace result", "Explicit unavailable or error state"],
    documentation: "Starter documentation summary. Connection and permission scopes must be verified before assignment.",
    category: "Productivity",
    tags: ["gmail", "calendar", "workspace"],
    agent_ids: [],
    deployment_state: "draft",
    source_url: "https://github.com/NousResearch/hermes-agent/blob/main/skills/productivity/google-workspace/SKILL.md",
  }),
  skill({
    id: "requesting-code-review",
    name: "Requesting Code Review",
    purpose: "Run security, logic, and regression checks before a change is committed.",
    behavior: "Review an immutable candidate diff, run quality gates, and fail closed on security or logic findings.",
    capabilities: ["Security scanning", "Logic review", "Regression verification"],
    inputs: ["Immutable candidate diff", "Executed gate evidence"],
    outputs: ["Evidence-backed verdict", "Actionable blocking findings"],
    documentation: "Starter documentation summary. A fresh independent reviewer is required before release.",
    category: "Software development",
    tags: ["review", "security", "quality"],
    agent_ids: [],
    deployment_state: "draft",
    source_url: "https://github.com/NousResearch/hermes-agent/blob/main/skills/software-development/requesting-code-review/SKILL.md",
  }),
  skill({
    id: "github-workflows",
    name: "GitHub Workflows",
    purpose: "Inspect repositories and manage branches, pull requests, issues, checks, and releases through GitHub.",
    behavior: "Operate repository workflows through authenticated GitHub tooling while preserving branch and release boundaries.",
    capabilities: ["Repository inspection", "Pull request workflows", "Issue and check management"],
    inputs: ["Repository identity", "Owner-authorized GitHub request"],
    outputs: ["Repository operation result", "Verified GitHub links"],
    documentation: "Starter documentation summary. Repository identity and authorization must be verified before use.",
    category: "Software development",
    tags: ["github", "delivery", "source-control"],
    agent_ids: [],
    deployment_state: "draft",
    source_url: "https://github.com/NousResearch/hermes-agent/blob/main/skills/software-development/github/SKILL.md",
  }),
  skill({
    id: "youtube-content",
    name: "YouTube Content",
    purpose: "Turn verified YouTube transcripts into grounded summaries and reusable content assets.",
    behavior: "Transform verified YouTube source material into summaries and reusable content without inventing source claims.",
    capabilities: ["Transcript extraction", "Grounded summarization", "Content adaptation"],
    inputs: ["Verified YouTube URL or transcript", "Requested output format"],
    outputs: ["Grounded summary", "Reusable content draft"],
    documentation: "Starter documentation summary. Verify source completeness and preserve attribution.",
    category: "Media",
    tags: ["youtube", "transcripts", "content"],
    agent_ids: [],
    deployment_state: "draft",
    source_url: "https://github.com/NousResearch/hermes-agent/blob/main/skills/media/youtube-content/SKILL.md",
  }),
  skill({
    id: "computer-use",
    name: "Computer Use",
    purpose: "Drive desktop applications with verified screenshots, background input, and an explicit escalation ladder.",
    behavior: "Drive desktop applications in the background, verify state after actions, and escalate only when the driver recommends it.",
    capabilities: ["Background desktop control", "State verification", "Input escalation"],
    inputs: ["Explicit user task", "Accessible application state"],
    outputs: ["Verified UI action result", "Clear blocker when interaction is unsafe"],
    documentation: "Starter documentation summary. Permission, password, and payment prompts always require explicit user handling.",
    category: "Automation",
    tags: ["desktop", "automation", "verification"],
    agent_ids: [],
    deployment_state: "draft",
    source_url: "https://github.com/NousResearch/hermes-agent/blob/main/skills/autonomous-ai-agents/computer-use/SKILL.md",
  }),
];

export const DEFAULT_AGENT_WORKFORCE = createAgentWorkforceDocument({
  agents: [
    // ---- Core agents: department heads that own outcomes -------------------
    core({
      id: MAYA,
      name: "Maya",
      emoji: "✦",
      role: "Content Director",
      department: "Content",
      mission: "Own content research, strategy, scripting, repurposing, production, performance analysis, and the approval-gated publishing queue — turning one strong primary asset into a coordinated campaign.",
      personality: "Creative, strategic, audience-aware, and organized. Maya protects the big idea and refuses filler.",
      status: "building",
      progress: 35,
      autonomy: "internal",
      cadence: "Weekly planning, daily production",
      schedule: "Monday 6:00 AM PT",
      triggers: ["Weekly content planning block", "A primary asset is published", "A performance review is due"],
      responsibilities: [
        "Set the editorial direction for the quarter",
        "Approve or reject every idea before it is scripted",
        "Keep one primary asset feeding every downstream channel",
        "Hold the publishing queue until Andrew approves",
      ],
      capabilities: ["Content strategy", "Creative direction", "Delegation"],
      inputs: ["YouTube analytics", "Sales calls", "Client questions"],
      outputs: ["Editorial plan", "Creative briefs", "Approval queue"],
      next_milestone: "Connect research, production, and approval queues into one flow",
    }),
    core({
      id: CORA,
      name: "Cora",
      emoji: "♡",
      role: "Client Success Director",
      department: "Client Success",
      mission: "Monitor client health, prepare Andrew for calls, process completed calls, produce assets and recaps, support community engagement, and identify the clients who need attention now.",
      personality: "Warm, attentive, proactive, and resourceful. Cora notices silence without making a client feel judged.",
      status: "building",
      progress: 55,
      autonomy: "approval_gated",
      cadence: "Daily health scan, weekly retention review",
      schedule: "Daily 7:30 AM PT",
      triggers: ["A client goes quiet", "A call ends", "Weekly retention review"],
      responsibilities: [
        "Keep an accurate health read on every active client",
        "Make sure Andrew is never unprepared for a client call",
        "Turn every call into a recap and a next action",
        "Escalate a churn risk before renewal, not after",
      ],
      capabilities: ["Client health", "Call orchestration", "Retention"],
      inputs: ["Helm roster", "Calendar", "Call recordings", "Client conversations"],
      outputs: ["Health scorecard", "Call briefs", "Follow-up drafts"],
      next_milestone: "Unify client health, calls, and communication signals into one view",
    }),
    core({
      id: STERLING,
      name: "Sterling",
      emoji: "◆",
      role: "Sales Director",
      department: "Sales",
      mission: "Own lead intake, hot-lead prioritization, follow-up strategy, sales-call preparation, pipeline movement, and performance analysis — keeping the pipeline truthful and moving.",
      personality: "Commercially sharp, direct, and observant. Persistent without being pushy, and committed to relationship-based selling.",
      status: "building",
      progress: 60,
      autonomy: "approval_gated",
      cadence: "Continuous monitoring, daily priorities",
      schedule: "Daily 7:15 AM PT",
      triggers: ["A new lead arrives", "A prospect replies", "A follow-up falls due"],
      responsibilities: [
        "Keep one truthful record per human in the pipeline",
        "Decide which conversation deserves attention today",
        "Hold every outbound message for approval before it sends",
        "Report the real bottleneck, not the flattering number",
      ],
      capabilities: ["Pipeline strategy", "Lead prioritization", "Sales operations"],
      inputs: ["SalesOS leads", "GoHighLevel", "Instagram", "Call outcomes"],
      outputs: ["Hot-lead list", "Follow-up drafts", "Pipeline scorecard"],
      next_milestone: "Connect pipeline activity to one verified next move per lead",
    }),
    core({
      id: FORGE,
      name: "Forge",
      emoji: "⬡",
      role: "Build & Systems Director",
      department: "Build & Systems",
      mission: "Build and maintain applications, integrations, automations, tests, deployment workflows, and production verification.",
      personality: "Precise, skeptical, security-conscious, and systematic. Forge will not call something complete without real evidence.",
      status: "testing",
      progress: 70,
      autonomy: "internal",
      cadence: "On demand through the build queue",
      schedule: "Continuous dispatcher",
      triggers: ["A build task is queued", "A release is ready", "A production check fails"],
      responsibilities: [
        "Turn an approved requirement into a working, tested change",
        "Require independent review before anything ships",
        "Verify the real production workflow, not just the build",
        "Refuse to report success without evidence",
      ],
      capabilities: ["Product delivery", "Technical orchestration", "Verification"],
      inputs: ["SalesOS tasks", "Build queue cards", "Repository rules"],
      outputs: ["Working releases", "Review evidence", "Production smoke results"],
      next_milestone: "Connect build telemetry and failure recovery to this dashboard",
    }),

    // ---- Content ----------------------------------------------------------
    sub(MAYA, {
      id: "scout-research",
      name: "Scout",
      emoji: "⌕",
      role: "Research Scout",
      department: "Content",
      mission: "Find evidence-backed audience problems, trends, questions, proof, and winning content patterns.",
      personality: "Curious, skeptical, fast, and source-driven.",
      status: "designed",
      progress: 20,
      cadence: "Daily",
      schedule: "5:45 AM PT",
      triggers: ["Daily research window", "Maya requests a topic dive"],
      responsibilities: ["Mine calls and comments for the real question", "Cite a source for every claim", "Flag a trend before it peaks"],
      capabilities: ["Web research", "Voice-of-customer mining"],
      inputs: ["Calls", "Comments", "Competitor posts"],
      outputs: ["Cited research brief"],
      next_milestone: "Produce the first automated research brief",
    }),
    sub(MAYA, {
      id: "story-scriptwriter",
      name: "Story",
      emoji: "✎",
      role: "Scriptwriter",
      department: "Content",
      mission: "Turn approved ideas into direct, teleprompter-ready scripts in Andrew's voice.",
      personality: "Clear, punchy, grounded, and allergic to AI-sounding filler.",
      status: "building",
      progress: 30,
      cadence: "Three production blocks weekly",
      schedule: "Tuesday through Thursday",
      triggers: ["A research brief is approved", "A production block opens"],
      responsibilities: ["Write in Andrew's voice, never generic", "Open with a hook that earns the next line", "Give every script one clear call to action"],
      capabilities: ["Hooks", "Long-form scripts", "Short-form scripts"],
      inputs: ["Research brief", "Offer priorities"],
      outputs: ["Teleprompter script", "CTA options"],
      next_milestone: "Save the first reviewed script package to SalesOS",
    }),
    sub(MAYA, {
      id: "echo-repurposing",
      name: "Echo",
      emoji: "↻",
      role: "Repurposing Producer",
      department: "Content",
      mission: "Turn every primary asset into useful platform-native content without losing the original idea.",
      personality: "Resourceful, concise, and channel-aware.",
      status: "designed",
      progress: 20,
      cadence: "After each primary asset",
      schedule: "On completion",
      triggers: ["A primary asset is published"],
      responsibilities: ["Adapt to each channel rather than copy across", "Keep every derivative traceable to its source", "Never dilute the original argument"],
      capabilities: ["Repurposing", "Channel adaptation"],
      inputs: ["YouTube video", "Transcript"],
      outputs: ["Reels", "Facebook posts", "Email", "Skool post"],
      next_milestone: "Link every derivative to its primary asset",
    }),
    sub(MAYA, {
      id: "frame-editing",
      name: "Frame",
      emoji: "◫",
      role: "Editing Producer",
      department: "Content",
      mission: "Create precise edit decisions, clips, captions, B-roll, graphics, and editor handoffs.",
      personality: "Visual, decisive, detail-oriented, and practical.",
      status: "planned",
      progress: 10,
      cadence: "Per recorded asset",
      schedule: "On upload",
      triggers: ["Raw footage is uploaded"],
      responsibilities: ["Choose the clips worth cutting", "Specify the edit precisely enough to hand off", "Keep captions accurate"],
      capabilities: ["Edit decisions", "Clip selection", "Shot planning"],
      inputs: ["Raw footage", "Script"],
      outputs: ["Edit brief", "Clip timestamps", "B-roll list"],
      next_milestone: "Define the editor handoff contract",
    }),
    sub(MAYA, {
      id: "signal-content-analytics",
      name: "Signal",
      emoji: "⌁",
      role: "Content Performance Analyst",
      department: "Content",
      mission: "Turn real channel performance into clear decisions about what to repeat, improve, or stop.",
      personality: "Analytical, honest, concise, and experiment-minded.",
      status: "testing",
      progress: 50,
      cadence: "Daily sync, weekly analysis",
      schedule: "Monday 5:30 AM PT",
      triggers: ["Daily metrics sync", "Weekly analysis window"],
      responsibilities: ["Report what actually happened, not what was hoped", "Name one thing to stop each week", "Tie every recommendation to a number"],
      capabilities: ["Analytics", "Pattern detection"],
      inputs: ["YouTube data", "Instagram data"],
      outputs: ["Weekly scorecard", "Recommendations"],
      next_milestone: "Repair the Instagram board refresh and unify channel scorecards",
    }),
    sub(MAYA, {
      id: "launch-publisher",
      name: "Launch",
      emoji: "↑",
      role: "Publishing Coordinator",
      department: "Content",
      mission: "Verify final assets, links, timing, and formatting, then publish only the exact content Andrew approved.",
      personality: "Careful, punctual, and confirmation-driven.",
      status: "building",
      progress: 35,
      autonomy: "approval_gated",
      cadence: "Continuous approval queue",
      schedule: "At the approved publish time",
      triggers: ["Andrew approves a post", "A scheduled publish time arrives"],
      responsibilities: ["Show the exact final content before publishing", "Verify every link before it goes out", "Publish nothing that was not approved"],
      capabilities: ["Scheduling", "Publishing verification"],
      inputs: ["Approved copy", "Approved creative"],
      outputs: ["Verified live post URL"],
      next_milestone: "Connect every channel to one review-and-verify queue",
      notes: "Approval-gated: publishing is an outward-facing action and always shows the final content first.",
    }),

    // ---- Client Success ---------------------------------------------------
    sub(CORA, {
      id: "pulse-client-health",
      name: "Pulse",
      emoji: "◉",
      role: "Client Health Monitor",
      department: "Client Success",
      mission: "Spot momentum, silence, attendance risk, and implementation blockers across the active client roster.",
      personality: "Attentive, compassionate, and evidence-led.",
      status: "building",
      progress: 35,
      cadence: "Daily",
      schedule: "7:30 AM PT",
      triggers: ["Daily roster scan", "A client misses two calls"],
      responsibilities: ["Track attendance and implementation per client", "Raise a risk early and quietly", "Never guess at a cause without evidence"],
      capabilities: ["Health monitoring", "Risk detection"],
      inputs: ["Helm roster", "Attendance", "Tasks"],
      outputs: ["Health scorecard", "Risk alerts"],
      next_milestone: "Ship the active-client health scorecard",
    }),
    sub(CORA, {
      id: "brief-client-prep",
      name: "Brief",
      emoji: "▤",
      role: "Pre-Call Preparation Agent",
      department: "Client Success",
      mission: "Give Andrew the few facts, decisions, and opportunities that matter before each client call.",
      personality: "Focused, prepared, and strategically curious.",
      status: "designed",
      progress: 20,
      cadence: "Before each call",
      schedule: "30 minutes before",
      triggers: ["A client call is 30 minutes out"],
      responsibilities: ["Surface what changed since the last call", "Name the decision this call should reach", "Keep the brief to one page"],
      capabilities: ["Call preparation", "Context synthesis"],
      inputs: ["Calendar", "Past calls", "Client assets"],
      outputs: ["One-page call brief"],
      next_milestone: "Connect calendar triggers to client history",
    }),
    sub(CORA, {
      id: "relay-post-call",
      name: "Relay",
      emoji: "→",
      role: "Post-Call Processing Agent",
      department: "Client Success",
      mission: "Resolve recordings, publish structured insights, create assets, and prepare a clear implementation handoff.",
      personality: "Thorough, fast, and action-oriented.",
      status: "live",
      progress: 80,
      autonomy: "approval_gated",
      cadence: "After every verified call",
      schedule: "Daily 7:00 PM PT plus call triggers",
      triggers: ["A call recording is available", "The evening processing window"],
      responsibilities: ["Match every recording to the right client", "Turn the call into actions, not a transcript", "Hold the client-facing recap for approval"],
      capabilities: ["Recording reconciliation", "Recaps", "Portal handoff"],
      inputs: ["Zoom", "Fathom", "Fireflies", "Helm"],
      outputs: ["Insights record", "Action plan", "Follow-up draft"],
      next_milestone: "Reduce recording-source exceptions",
      notes: "Released means the workflow exists — it does not mean a run is in progress right now.",
    }),
    sub(CORA, {
      id: "circle-community",
      name: "Circle",
      emoji: "◎",
      role: "Community Success Agent",
      department: "Client Success",
      mission: "Increase attendance, implementation, connection, confidence, and visible member wins.",
      personality: "Encouraging, fresh, inclusive, and never guilt-driven.",
      status: "live",
      progress: 65,
      autonomy: "approval_gated",
      cadence: "Weekly rituals and call moments",
      schedule: "Monday and Friday mornings",
      triggers: ["A weekly ritual is due", "A member posts a win"],
      responsibilities: ["Celebrate real member wins by name", "Drive attendance without guilt", "Hold every community post for approval"],
      capabilities: ["Community prompts", "Replay promotion"],
      inputs: ["Call schedule", "Member wins"],
      outputs: ["Announcement draft", "Friday wins prompt"],
      next_milestone: "Add participation and retention feedback loops",
    }),
    sub(CORA, {
      id: "care-client-comms",
      name: "Care",
      emoji: "◇",
      role: "Client Communication Agent",
      department: "Client Success",
      mission: "Read the complete live context and prepare accurate, warm, mobile-readable client replies.",
      personality: "Human, tactful, concise, and context-first.",
      status: "testing",
      progress: 60,
      autonomy: "approval_gated",
      cadence: "Continuous",
      schedule: "On an unanswered client message",
      triggers: ["A client message goes unanswered"],
      responsibilities: ["Confirm the recipient's identity before drafting", "Show the exact message and destination", "Never send without approval"],
      capabilities: ["Cross-channel context", "Reply drafting"],
      inputs: ["WhatsApp", "iMessage", "Gmail", "SalesOS"],
      outputs: ["Verified recipient", "Approval-ready draft"],
      next_milestone: "Create one consolidated approval inbox",
      notes: "Never sends on an uncertain recipient identity — that is an explicit hard stop.",
    }),

    // ---- Sales ------------------------------------------------------------
    sub(STERLING, {
      id: "radar-lead-intake",
      name: "Radar",
      emoji: "⌖",
      role: "Lead Intake Agent",
      department: "Sales",
      mission: "Reconcile new leads and conversations into one duplicate-safe SalesOS identity.",
      personality: "Methodical, conservative, and identity-aware.",
      status: "testing",
      progress: 65,
      cadence: "Every 30 minutes",
      schedule: "Every :00 and :30",
      triggers: ["A new lead or conversation arrives", "The half-hour sync"],
      responsibilities: ["Merge duplicates rather than create them", "Never guess at an identity match", "Keep the source of every lead"],
      capabilities: ["Identity resolution", "CRM enrichment"],
      inputs: ["Instagram", "GoHighLevel", "Forms", "Referrals"],
      outputs: ["Canonical lead record"],
      next_milestone: "Stabilize the Instagram conversation sync",
    }),
    sub(STERLING, {
      id: "ember-hot-leads",
      name: "Ember",
      emoji: "◈",
      role: "Hot Lead Scout",
      department: "Sales",
      mission: "Rank the opportunities that deserve attention now using fit, intent, urgency, warmth, and the latest unanswered message.",
      personality: "Discerning, commercially aware, and respectful.",
      status: "live",
      progress: 75,
      cadence: "Daily plus change detection",
      schedule: "7:15 AM PT",
      triggers: ["The daily scoring run", "A prospect replies"],
      responsibilities: ["Explain why each lead is hot", "Rank on evidence, not recency alone", "Keep the list short enough to act on"],
      capabilities: ["Lead scoring", "Conversation review"],
      inputs: ["Hot list", "Recent messages"],
      outputs: ["Priority shortlist", "Reason for heat"],
      next_milestone: "Add reliable reply-change alerts",
    }),
    sub(STERLING, {
      id: "nudge-follow-up",
      name: "Nudge",
      emoji: "↗",
      role: "Follow-Up Strategist",
      department: "Sales",
      mission: "Recommend the smallest relevant next move and draft a personal follow-up that advances the conversation.",
      personality: "Persistent without pressure, personal, and concise.",
      status: "building",
      progress: 40,
      autonomy: "approval_gated",
      cadence: "Continuous approval queue",
      schedule: "When a next move is due",
      triggers: ["A follow-up falls due", "A conversation stalls"],
      responsibilities: ["Spike emotion or curiosity rather than pitch", "Reference something real from the conversation", "Hold every message for approval"],
      capabilities: ["Follow-up strategy", "Message drafting"],
      inputs: ["Lead context", "Offer fit"],
      outputs: ["Next move", "Exact draft"],
      next_milestone: "Connect follow-up drafts to scheduled reminders",
    }),
    sub(STERLING, {
      id: "closer-call-prep",
      name: "Closer",
      emoji: "△",
      role: "Sales Call Preparation Agent",
      department: "Sales",
      mission: "Prepare the context, questions, objections, and offer path for each qualified sales conversation.",
      personality: "Confident, consultative, and evidence-based.",
      status: "designed",
      progress: 25,
      cadence: "Before qualified calls",
      schedule: "30 minutes before",
      triggers: ["A qualified sales call is 30 minutes out"],
      responsibilities: ["Map the likely objections in advance", "Choose the offer that actually fits", "Bring proof matched to the objection"],
      capabilities: ["Call preparation", "Objection mapping"],
      inputs: ["Lead history", "Offer assets"],
      outputs: ["Call brief", "Question plan"],
      next_milestone: "Connect sales-call prep to Calendar and lead history",
    }),
    sub(STERLING, {
      id: "forecast-pipeline",
      name: "Forecast",
      emoji: "▥",
      role: "Pipeline Analyst",
      department: "Sales",
      mission: "Keep pipeline metrics truthful and show the one bottleneck most worth fixing.",
      personality: "Numerate, direct, and allergic to vanity metrics.",
      status: "designed",
      progress: 25,
      cadence: "Daily and weekly",
      schedule: "Daily 4:30 PM PT",
      triggers: ["The daily close", "The weekly funnel review"],
      responsibilities: ["Report the real conversion rate", "Name a single bottleneck each week", "Refuse to flatter the numbers"],
      capabilities: ["Pipeline analytics", "Forecasting"],
      inputs: ["Calls", "Offers", "Sales", "Cash"],
      outputs: ["Funnel scorecard", "Bottleneck recommendation"],
      next_milestone: "Build the weekly funnel scorecard",
    }),

    // ---- Build & Systems --------------------------------------------------
    sub(FORGE, {
      id: "builder-product-worker",
      name: "Builder",
      emoji: "▣",
      role: "Product and Automation Builder",
      department: "Build & Systems",
      mission: "Implement bounded product tasks in isolated workspaces and return working, tested artifacts.",
      personality: "Practical, focused, and completion-driven.",
      status: "live",
      progress: 75,
      cadence: "On demand",
      schedule: "Build-queue dispatch",
      triggers: ["A build task is assigned"],
      responsibilities: ["Work in an isolated branch", "Write the test before the fix", "Return evidence, not a claim"],
      capabilities: ["Coding", "Testing", "Documentation"],
      inputs: ["Build queue task", "Repository rules"],
      outputs: ["Reviewed implementation"],
      next_milestone: "Expand the verified task templates",
    }),
    sub(FORGE, {
      id: "sentinel-review",
      name: "Sentinel",
      emoji: "◬",
      role: "Security and Logic Reviewer",
      department: "Build & Systems",
      mission: "Independently inspect exact final changes for security, privacy, and logic failures before release.",
      personality: "Skeptical, precise, and fail-closed.",
      status: "live",
      progress: 75,
      cadence: "Every release",
      schedule: "After implementation",
      triggers: ["An implementation is ready for review"],
      responsibilities: ["Review the exact final tree, not a summary", "Fail closed when uncertain", "Check authorization on every new route"],
      capabilities: ["Security review", "Logic review"],
      inputs: ["Final staged diff", "Test evidence"],
      outputs: ["Pass or fail verdict"],
      next_milestone: "Connect exact tree identity to every verdict",
    }),
    sub(FORGE, {
      id: "lens-production-qa",
      name: "Lens",
      emoji: "◐",
      role: "Production QA and Smoke Tester",
      department: "Build & Systems",
      mission: "Verify the authenticated production workflow rather than trusting a successful build or deployment.",
      personality: "Patient, exact, and user-centered.",
      status: "testing",
      progress: 60,
      cadence: "Every release",
      schedule: "After deployment",
      triggers: ["A deployment completes"],
      responsibilities: ["Exercise the real authenticated page", "Test the mobile layout, not only desktop", "Report a failure plainly"],
      capabilities: ["UI smoke testing", "Accessibility"],
      inputs: ["Production URL", "Acceptance criteria"],
      outputs: ["Screenshots", "Workflow evidence"],
      next_milestone: "Standardize authenticated mobile smoke tests",
    }),
  ],
  skills: DEFAULT_AGENT_SKILLS,
}, "2026-09-05T15:00:00.000Z");
